const HOWS_MY_DRIVING_NY_API_DOMAIN = 'https://api.howsmydrivingny.nyc'
export const HOWS_MY_DRIVING_NY_NEW_LOOKUP_ENDPOINT = `${HOWS_MY_DRIVING_NY_API_DOMAIN}/api/v1/`
export const HOWS_MY_DRIVING_NY_PREVIOUS_LOOKUP_ENDPOINT = `${HOWS_MY_DRIVING_NY_API_DOMAIN}/api/v1/lookup/`