import {
  BUS_LANE_CAMERA_VIOLATION_CODE,
  MOBILE_BUS_LANE_CAMERA_VIOLATION_CODE,
  RED_LIGHT_CAMERA_VIOLATION_CODE,
  SCHOOL_ZONE_SPEED_CAMERA_VIOLATION_CODE,
} from 'constants/violations'

export type NonParkingViolationCode =
  | typeof BUS_LANE_CAMERA_VIOLATION_CODE
  | typeof MOBILE_BUS_LANE_CAMERA_VIOLATION_CODE
  | typeof RED_LIGHT_CAMERA_VIOLATION_CODE
  | typeof SCHOOL_ZONE_SPEED_CAMERA_VIOLATION_CODE
